{% set name = "nose-cov" %}
{% set version = "1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8bec0335598f1cc69e3262cc50d7678c1a6010fa44625ce343c4ec1500774412

build:
  number: 2
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - nose >=0.11.4
    - cov-core >=1.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - nose_cov
  commands:
    - nosetests --help
    - nosetests --plugins

about:
  home: http://bitbucket.org/memedough/nose-cov/overview
  license: MIT
  license_file: LICENSE.txt
  summary: 'nose plugin for coverage reporting, including subprocesses and multiprocessing'
  license_family: MIT

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
