travis:
  secure:
    BINSTAR_TOKEN: FoIZZzrPzI6GllrMbWepJF5MnnEn2ItLz53Kh29v99FAVshq4Ayly5CNLfy3/PiY+0yjQjaoWFQwXyYvTtMjyNEdj+zGBtwbWMqXyuV6Ae+8CuGQAG7BTDTRXH3BC/i3DXT7RVDf+/Xp8pYXcok1egbGyWKPiH4b4XLGTC4Dnot7Uvf0z+NgUGn9/d36Dt6X0We7R1PMyDpQHsmk80Tz0JoJSQLX69q5QQP51AzO2M/B+mhhnS/jPQd8QOmI49rVR/y5GPwd02twihL8CDdMQcowTLyt+kdL0lpAOU13e/0EWqoYp5RUGcohZA0Vvvbw4qqRMtXWDMzJ8M8VsTLdCrB/x32fdLnQ49xXMCPCPwy/iTD9zuZ5GDICq02TrcbGi85HRRJ8rWlqnRKtAVbMS+9gMr+jkbhkJfZWV2valIwB3PLv1W6Btc/qev8cJldFBICOBI2gvVEPtaZGMHP3Jhje3dnJFnr8c7zsQKL0zIYJb4o/k/PlzBoWuwYFj/nrVxI73qcbjWAqGgfzrLA9FOEWcsspPvbrm/W1ULNetQISmAG/+zapPFyW4LqGg/k7QLM9ezwCB715jySRERkTp+ufb4rDcrAidqHET8JeHgA8SfhU9HgrxxKuoP9pgDHSerYzwsTkYcfPkNY17q/lNQjpplooIw6dWiQ4y8kbKlk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
